### ISSUE TITLE
Installing GMT and dependencies and configuration and hw1 examples

### ISSUE THREAD

**Issue by cmpuskas** [GenericMappingTools/2020-unavco-course#24] opened 2020-07-15 13:08 UTC
After we spoke at the GMT help session, I thought I'd better write down my questions, since there multiple issues.

1.  Installation - I downloaded the MacOS bundle and dragged the GMT icon to my applications folder for my mac with Mojave 10.14.6.  Then I opened the app and followed the instructions on the GMT bash window on how to set my paths.  I downloaded the homework examples and ran them without modification in a separate terminal window.

2. The hw1 examples - The examples ran and worked, except count.mp4/count.webm was rotated. I've occasionally had this problem in GMT5, where I specified portrait mode and still ended up in landscape mode.  Not sure if this is a serious issue, or unique to my computer, but please let me know if the GMT development team knows anything about this.

3. Warning messages - running the test scripts generates a lot of messages, so I may have missed one.  Do I need to be concerned, or is there anything I can do about these messages:

> gmt [ERROR]: TIME_LANGUAGE given illegal value (us)!
> 1 GMT Defaults conversion errors in file /Users/puskas/gmt.conf!
> end [INFORMATION]: Destroying the current workflow directory /Users/puskas/.gmt/sessions/gmt_session.61742
> end [INFORMATION]: Destroying the current workflow directory /Users/puskas/.gmt/sessions/gmt_session.61752
> begin [INFORMATION]: Creating a workflow directory /Users/puskas/.gmt/sessions/gmt_session.61974
> begin [ERROR]: Unrecognized keyword TIME_LANGUAGE. You may have been using a deprecated GMT3 or GMT4 keyword.
> Change keyword or use with GMT_COMPATIBILITY=4. Please see https://docs.generic-mapping-tools.org/6.1/changes.html#new-features-in-gmt-5 for more information.
> 
> gmt [WARNING]: GMT_COMPATIBILITY: Expects values from 6 to 6; reset to 6. [Repeated many times]

3.  Configuration - I don't see a configuration file in the hw1 directory like gmt.conf or .gmtdefaults.  Is there a separate list of default settings in a file somewhere, and would this affect the messages I see while running a script?

4. Dependencies - The GMT bash window and an email from yesterday assured me that I needed to download several dependencies.  So I tried installing the dependencies from https://github.com/GenericMappingTools/gmt/wiki/Install-dependencies-on-macOS-via-MacPorts, with mixed results.  I used MacPorts for the attempted install.

- "sudo port install cmake curl netcdf" did not work.  I already have cmake 3.17.3 and curl 7.65.3.  Is this command supposed to install cmake, curl, and netcdf separately, or is "curl netcdf" some kind of list of options in this case? Netcdf is failing to install separately, because there is an issue with Xcode.
- gdal installed ok
- pcre2, fft2-3-single, ghostscript did not install because there is something wrong with Xcode.  The App Store won’t let me upgrade Xcode without upgrading my OS, which I am reluctant to do because it will break some older software I have.
- glib2 did not install because of “Failed to configure postgresql83”.  The current version of postgresql is at ~95, the problem might be something else entirely.

**Comment by PaulWessel** [comment] 2020-07-15 16:52
Looks like you have some old gmt.conf files laying around, probably in your home directory.  Please delete.  it is likely the cause of your warnings and rotation of the plot.
Dependencies: None needed since you installed from the macos installer - it has everything.
You are welcome to follow the general installation from macports if you like since macports now offers 6.1, but no need if everything is working with the bundle.

**Comment by cmpuskas** [comment] 2020-07-15 17:16
Thank you very much for your quick response.  I deleted the gmt.conf file in my home directory and that indeed helped with the rotation.  I will stop trying to install dependencies if they do not require separate installation.

		—Christine

**Comment by PaulWessel** [comment] 2020-07-15 18:19
Sounds good.  Closing this issue - open another if any more trouble.

**Closed as completed by PaulWessel** 2020-07-15 18:19 UTC
